export const mockLocations = {
	districts: [
		'Kampala', 'Wakiso', 'Mukono', 'Mbarara', 'Gulu', 'Mbale', 'Jinja', 'Arua',
		'Hoima', 'Lira', 'Masaka', 'Kabale', 'Soroti', 'Mbarara City', 'Jinja City',
		'Mbale City', 'Gulu City', 'Lira City', 'Soroti City', 'Arua City', 'Masaka City',
		'Kampala Capital City', 'Bukomansimbi', 'Butambala', 'Buvuma', 'Gomba', 'Kalangala',
		'Kalungu', 'Kasanda', 'Kyotera', 'Lwengo', 'Lyantonde', 'Mpigi', 'Rakai', 'Sembabule',
		'Kayunga', 'Kiboga', 'Kyankwanzi', 'Luwero', 'Mityana', 'Mubende', 'Nakaseke',
		'Nakasongola', 'Bugiri', 'Bugweri', 'Buyende', 'Iganga', 'Kaliro', 'Kamuli',
		'Luuka', 'Mayuge', 'Namayingo', 'Namutumba', 'Buliisa', 'Kagadi', 'Kakumiro',
		'Kibaale', 'Kiryandongo', 'Masindi', 'Kabarole', 'Kamwenge', 'Kyegegwa', 'Kyenjojo',
		'Bushenyi', 'Ibanda', 'Isingiro', 'Ntungamo', 'Rubirizi', 'Sheema', 'Kanungu',
		'Kisoro', 'Rukiga', 'Rukungiri', 'Rubanda', 'Bundibugyo', 'Kasese', 'Ntoroko',
		'Bunyangabu', 'Kikuube', 'Kitagwenda', 'Kazo', 'Kiruhura', 'Budaka', 'Busia',
		'Butaleja', 'Butebo', 'Kibuku', 'Pallisa', 'Tororo', 'Bulambuli', 'Bududa',
		'Manafwa', 'Namisindwa', 'Sironko', 'Kween', 'Kapchorwa', 'Amuria', 'Kaberamaido',
		'Katakwi', 'Kumi', 'Ngora', 'Serere', 'Abim', 'Amudat', 'Kaabong', 'Karenga',
		'Kotido', 'Moroto', 'Napak', 'Nakapiripirit', 'Nabilatuk', 'Agago', 'Amuru',
		'Kitgum', 'Lamwo', 'Nwoya', 'Omoro', 'Pader', 'Alebtong', 'Apac', 'Dokolo',
		'Kwania', 'Otuke', 'Oyam', 'Kole', 'Koboko', 'Maracha', 'Moyo', 'Nebbi',
		'Obongi', 'Pakwach', 'Terego', 'Yumbe', 'Zombo', 'Madi-Okollo', 'Adjumani',
		'Amolatar', 'Buhweju', 'Kapelebyong'
	],
	citiesByDistrict: {
		Kampala: ['Kampala', 'Kampala Central', 'Kawempe', 'Makindye', 'Nakawa', 'Rubaga'],
		Wakiso: ['Wakiso', 'Entebbe', 'Nansana', 'Kira', 'Ssabagabo'],
		Mukono: ['Mukono', 'Seeta', 'Njeru'],
		Mbarara: ['Mbarara'],
		'Mbarara City': ['Mbarara City'],
		Gulu: ['Gulu'],
		'Gulu City': ['Gulu City'],
		Mbale: ['Mbale'],
		'Mbale City': ['Mbale City'],
		Jinja: ['Jinja', 'Buwenge'],
		'Jinja City': ['Jinja City'],
		Arua: ['Arua'],
		'Arua City': ['Arua City'],
		Hoima: ['Hoima'],
		Lira: ['Lira'],
		'Lira City': ['Lira City'],
		Masaka: ['Masaka'],
		'Masaka City': ['Masaka City'],
		Kabale: ['Kabale'],
		Soroti: ['Soroti'],
		'Soroti City': ['Soroti City'],
	},
	listingTypes: ['rent', 'sale'],
	propertyTypes: ['apartment', 'house', 'land', 'commercial'],
};

export const mockProperties = [
	{
		id: 1,
		title: 'Modern Apartment in Kololo',
		description: 'Two-bedroom apartment with balcony and parking.',
		district: 'Kampala',
		city: 'Kampala Central',
		price: 1800000,
		listingType: 'rent',
		bedrooms: 2,
		propertyType: 'apartment',
		latitude: 0.337,
		longitude: 32.585,
		imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=60',
	},
	{
		id: 2,
		title: 'Family House in Kira',
		description: 'Standalone home with a compound and servant quarter.',
		district: 'Wakiso',
		city: 'Kira',
		price: 320000000,
		listingType: 'sale',
		bedrooms: 4,
		propertyType: 'house',
		latitude: 0.395,
		longitude: 32.649,
		imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=60',
	},
	{
		id: 3,
		title: 'Retail Unit near Entebbe Road',
		description: 'Ground-floor commercial space with high foot traffic.',
		district: 'Wakiso',
		city: 'Entebbe',
		price: 2500000,
		listingType: 'rent',
		bedrooms: 0,
		propertyType: 'commercial',
		latitude: 0.12,
		longitude: 32.48,
		imageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=60',
	},
];

export const mockMessages = [
	{
		id: 1,
		subject: 'Inquiry: Modern Apartment in Kololo',
		body: 'Is this property still available for immediate move-in?',
		propertyId: 1,
		createdAt: '2026-05-01T10:30:00Z',
		from: 'tenant@example.com',
		to: 'agent@mycanopy.verbeek.ug.test',
	},
];
